set nocompatible

if has("syntax")
    syntax on
endif

if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line ("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

filetype off
filetype plugin indent on
set background=dark
set t_Co=256
colorscheme badwolf

autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4|set textwidth=79
autocmd FileType ruby set tabstop=2|set shiftwidth=2|set expandtab|set softtabstop=2|set textwidth=79
autocmd FileType * set tabstop=2|set shiftwidth=2|set expandtab|set softtabstop=2|set textwidth=120
autocmd FileType make setlocal noexpandtab

set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class,elsif,rescue,begin
let python_highlight_all = 1

set smartcase
set ignorecase
set showmatch
set smartindent
set number
set ls=2
set report=0
set ruler
set laststatus=2
set cursorline              " have a line indicate the cursor location
set linebreak               " don't wrap textin the middle of a word
set autoindent              " always set autoindenting on
set mouse=a
set modelines=0     " CVE-2007-2438
set nocompatible    " Use Vim defaults instead of 100% vi compatibility
set backspace=2     " more powerful backspacing

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
